### ISSUE TITLE
It looks like TypeScript definition is not correct

### ISSUE THREAD

**Issue by rstefko** [crouchcd/pkce-challenge#3] opened 2021-03-12 09:50 UTC
If I use

`import pkceChallenge from 'pkce-challenge';`

then

`const challenge = pkceChallenge(128);`

generates runtime error, because pkceChallenge is undefined.

**Comment by crouchcd** [comment] 2021-03-13 02:26
Can you share what the compile output looks like and/or what instructions you use to compile? I haven't been able to reproduce while trying with a variety of settings.

**Comment by crouchcd** [comment] 2021-05-20 02:06
@rstefko Can you provide more detail?

**Comment by crouchcd** [comment] 2021-05-26 15:46
Closing until further notice.

**Comment by meck93** [comment] 2021-08-09 14:15
@crouchcd To provide a little bit more context. I had a similar issue. 
The following code only worked once I enabled `esModuleInterop: true` in the `tsconfig.json`. 

```typescript
import * as pkceChallenge from "pkce-challenge";
```

**Comment by crouchcd** [comment] 2021-08-09 22:11
@meck93 Okay thanks for sharing. Yes, good idea to update the README with this information. BTW I had to explicitly use `default` with import star. I guess that's because, like the docs say, ES6 specs require an object for a namespace import. If that's okay, would you like to update README?

```js
import * as pkceChallenge from "pkce-challenge";

pkceChallenge.default();
```

**Closed** 2021-08-10 17:06 UTC
